import { BlogPost } from '../types';

export const DATA_POSTS: BlogPost[] = [
  {
    slug: 'why-csv-files-break-in-excel',
    title: 'Why your CSV breaks when Excel opens it',
    description: 'Leading zeros vanish, phone numbers turn into scientific notation and dates rearrange themselves. Every one of these has a specific cause and a fix.',
    excerpt: 'Excel guesses the type of every cell it opens. Those guesses have corrupted postcodes, product codes and, famously, human gene names.',
    category: 'data',
    tags: ['csv', 'excel', 'data-quality'],
    published: '2026-09-09',
    relatedTools: ['csv-viewer', 'csv-editor', 'csv-cleaner', 'delimiter-converter'],
    takeaways: [
      'Excel guesses a type for every cell it opens, and the guesses are destructive: leading zeros vanish and 16-digit numbers lose their last digits permanently.',
      'Use Data then From Text/CSV rather than double-clicking, and set identifier columns to Text.',
      'Excel splits on the operating system list separator, not always a comma, which is why the same file opens differently on two machines.',
      'A UTF-8 byte order mark fixes accented characters for Excel and breaks the first column name for most other parsers.',
    ],
    words: 739,
  },

  {
    slug: 'csv-to-json-conversion-guide',
    title: 'Converting CSV to JSON without losing your data',
    description: 'CSV is flat and typeless; JSON is nested and typed. The conversion involves real decisions about types, nulls and structure.',
    excerpt: 'Every CSV value is a string. Turning them into JSON means deciding which strings become numbers, and getting that wrong destroys IDs and postcodes.',
    category: 'data',
    tags: ['csv', 'json', 'conversion'],
    published: '2026-09-09',
    relatedTools: ['csv-to-json', 'json-to-csv', 'json-formatter', 'csv-cleaner'],
    takeaways: [
      'Every CSV value is a string, so any type inference is a guess. Keeping everything as a string and casting deliberately is the safe default.',
      'Losing a number type is recoverable; losing the leading zeros on an identifier is not.',
      'An empty CSV field could mean empty string, missing or null, and CSV cannot tell you which. Pick a convention and document it.',
      'Numbers beyond 2^53 are silently rounded by JavaScript, so long IDs must stay strings.',
    ],
    words: 752,
  },

  {
    slug: 'cleaning-messy-spreadsheet-data',
    title: 'Cleaning messy spreadsheet data: a repeatable order of operations',
    description: 'Duplicate rows, inconsistent casing, invisible whitespace and mixed date formats. A sequence that fixes them without creating new problems.',
    excerpt: 'Most "the data is wrong" problems are four or five specific defects. Fixing them in the right order matters, because some fixes mask others.',
    category: 'data',
    tags: ['data-cleaning', 'csv', 'duplicates'],
    published: '2026-09-09',
    relatedTools: ['csv-cleaner', 'remove-duplicates', 'find-replace', 'text-cleaner', 'csv-editor'],
    takeaways: [
      'Trim whitespace before anything else, because every later step compares strings and trailing spaces defeat all of them.',
      'Deduplicate after normalising, not before, or near-identical rows survive as distinct.',
      'Define what counts as a duplicate first. Same email, same name and date, and same whole row are three different answers.',
      'Merged cells, multiple header rows and totals at the bottom are structural problems no cell-level cleaning will fix.',
    ],
    words: 766,
  },

  {
    slug: 'csv-vs-excel-when-to-use-which',
    title: 'CSV or Excel? Choosing the right format for the job',
    description: 'CSV is a text format with no types and no formulas. XLSX is a compressed archive with everything. Each is the wrong choice in specific, predictable ways.',
    excerpt: 'A file that opens in Excel is not the same as an Excel file. The difference decides whether your formulas, formatting and column types survive.',
    category: 'data',
    tags: ['csv', 'excel', 'xlsx', 'formats'],
    published: '2026-09-09',
    relatedTools: ['csv-viewer', 'csv-editor', 'delimiter-converter', 'remove-duplicates'],
    takeaways: [
      'CSV is interoperable, streamable, diffable and durable. XLSX keeps types, formulas, multiple sheets and formatting.',
      'If the content is data, CSV is the better record. If the content is a presentation of data, XLSX is the better view.',
      'Keep the source as CSV and generate the spreadsheet from it, rather than treating the spreadsheet as the master copy.',
      'Every round trip through a spreadsheet is a chance for a silent type conversion to damage identifiers.',
    ],
    words: 636,
  },

  {
    slug: 'csv-delimiters-quoting-and-encoding',
    title: 'CSV delimiters, quoting and encoding: the three things that break files',
    description: 'RFC 4180 is one page long and widely ignored. Knowing the rules, and where real files depart from them, makes parsing failures diagnosable.',
    excerpt: 'A CSV that opens in column A on one machine and correctly on another is not corrupt. The two machines simply disagree about what CSV means.',
    category: 'data',
    tags: ['csv', 'rfc-4180', 'encoding', 'parsing'],
    published: '2026-09-09',
    relatedTools: ['delimiter-converter', 'csv-cleaner', 'tsv-converter', 'csv-viewer'],
    takeaways: [
      'The delimiter is not always a comma. Semicolons are standard across much of Europe, and nothing in the file declares which was used.',
      'A quoted field escapes an internal quote by doubling it, and a single record can legally span several physical lines.',
      'Write UTF-8, and add a byte order mark only when Excel is the intended consumer.',
      'When a file looks wrong, check the delimiter, the quoting and the encoding in that order, because each one masks the next.',
    ],
    words: 778,
  },

  {
    slug: 'what-actually-compresses-in-a-zip',
    title: 'Why zipping your photos saves nothing, and what to do instead',
    description: 'ZIP finds repetition. JPEGs have none left, which is why a folder of 200 photos zips to 199 MB. Here is what zipping is actually for.',
    excerpt: 'Zipping a folder of holiday photos and watching it shrink by 0.4% is not a broken tool. It is the correct answer to the wrong question.',
    category: 'data',
    tags: ['zip', 'compression', 'archives'],
    published: '2026-09-16',
    relatedTools: ['zip-creator', 'zip-extractor', 'batch-zip', 'merge-csv'],
    takeaways: [
      'ZIP removes repetition. Already-compressed formats like JPEG, PNG, MP4 and DOCX have none left, so they barely shrink.',
      'Text, CSV, logs and source code compress enormously, often to a tenth of their size.',
      'Zipping is still worth it for photos: one attachment instead of two hundred, with filenames and folders preserved.',
      'ZIP encryption comes in two kinds. The old one is broken; only AES-256 is worth trusting, and the filenames stay visible either way.',
    ],
    words: 809,
  },

  {
    slug: 'merging-csv-files-that-do-not-line-up',
    title: 'Merging CSV files whose columns do not line up',
    description: 'Combining exports is easy when the headers match and a data-loss trap when they do not. The failure is silent, which is the problem.',
    excerpt: 'Twelve monthly exports, one combined file. Two of the months added a column, one renamed another, and a naive concatenation hides all of it.',
    category: 'data',
    tags: ['csv', 'merge', 'data-cleaning'],
    published: '2026-09-17',
    relatedTools: ['merge-csv', 'csv-cleaner', 'remove-duplicates', 'csv-viewer'],
    takeaways: [
      'Compare header sets before merging. Same names in a different order, renamed columns and extra columns all produce different kinds of damage.',
      'Stacking rows and joining on a key are different operations. Stacking adds rows; joining adds columns and can multiply rows.',
      'Record which file each row came from. Without a source column, a wrong total is untraceable once the files are combined.',
      'Deduplicate on a real key, not on whole-row equality, or you will keep two copies of the same record that differ by a trailing space.',
    ],
    words: 750,
  },
];
