import { BlogPost } from '../types';

export const DEV_POSTS: BlogPost[] = [
  {
    slug: 'unicode-utf8-and-mojibake',
    title: 'Why your text turns into Ã©: Unicode, UTF-8 and mojibake explained',
    description: 'Encoding bugs produce a small, recognisable set of symptoms. Learning to read them tells you exactly where the pipeline went wrong.',
    excerpt: 'When "café" arrives as "cafÃ©", the bytes are fine, something decoded them with the wrong assumption. The garbled output tells you which assumption.',
    category: 'dev',
    tags: ['unicode', 'utf-8', 'encoding'],
    published: '2026-08-05',
    relatedTools: ['unicode-converter', 'ascii-converter', 'text-cleaner', 'binary-converter'],
    takeaways: [
      'Unicode is a catalogue of characters; an encoding is a rule for turning them into bytes. Most bugs are two systems disagreeing about the rule.',
      'One accented character becoming exactly two garbled ones is a UTF-8 read as Latin-1, and the data is still recoverable.',
      'One character becoming a single replacement symbol means the information is already gone.',
      'Normalise to NFC before comparing or storing, because the same visible character has more than one valid encoding.',
    ],
    words: 800,
  },

  {
    slug: 'json-errors-and-how-to-fix-them',
    title: 'The JSON errors everyone hits, and what the spec actually says',
    description: 'Trailing commas, single quotes, comments and big numbers. The five JSON mistakes that account for most parse failures, and how to spot them fast.',
    excerpt: 'JSON is a deliberately tiny format. Most parse errors come from writing JavaScript object syntax and expecting a JSON parser to accept it.',
    category: 'dev',
    tags: ['json', 'parsing', 'api'],
    published: '2026-08-08',
    relatedTools: ['json-formatter', 'json-to-csv', 'csv-to-json', 'yaml-formatter'],
    takeaways: [
      'Trailing commas, single quotes, unquoted keys and comments are all legal JavaScript and all illegal JSON.',
      'The error position usually points one character past the real problem, which is why people stare at the wrong line.',
      'Integers beyond 2^53 are silently rounded when parsed, so large IDs must be transported as strings.',
      'Duplicate keys are undefined behaviour in the specification, so different parsers legitimately disagree.',
    ],
    words: 727,
  },

  {
    slug: 'base64-encoding-explained',
    title: 'Base64, explained properly: what it is for and what it is not',
    description: 'Base64 turns binary into text at a 33% size cost. It is an encoding, not encryption, and using it as the latter is a recurring security mistake.',
    excerpt: 'Base64 shows up in data URIs, email attachments, JWTs and API payloads. It also shows up in security incident reports, because people mistake it for protection.',
    category: 'dev',
    tags: ['base64', 'encoding', 'binary'],
    published: '2026-08-15',
    relatedTools: ['base64', 'image-to-base64', 'base64-to-image', 'jwt-decoder'],
    takeaways: [
      'Base64 turns three bytes into four characters, a fixed 33% increase that no implementation avoids.',
      'It provides no confidentiality at all. Anyone can decode it instantly, with no key involved.',
      'Compress before encoding, never after, because base64 output compresses far worse than the original bytes.',
      'URLs and JWTs use base64url, which swaps two characters, so a standard decoder will reject it until they are swapped back.',
    ],
    words: 716,
  },

  {
    slug: 'how-diff-tools-find-changes',
    title: 'How diff tools work, and why they sometimes show the wrong change',
    description: 'Diff algorithms find the longest common subsequence between two texts. Knowing that explains misaligned hunks, and how to get a more useful comparison.',
    excerpt: 'A diff tool has no idea what your code means. It is solving a sequence-matching problem, which is why moved blocks look like a delete plus an unrelated insert.',
    category: 'dev',
    tags: ['diff', 'git', 'algorithms'],
    published: '2026-08-16',
    relatedTools: ['diff-checker', 'diff-text', 'word-compare', 'pdf-compare'],
    takeaways: [
      'A diff finds the longest common subsequence, so it is fast on similar files and slow on dissimilar ones.',
      'Granularity decides what you see: line-based is right for code, word-based for prose.',
      'Moved blocks show as a delete plus an insert, because the algorithm has no concept of a move.',
      'Normalise line endings and formatting first, or the real change disappears into whitespace noise.',
    ],
    words: 701,
  },

  {
    slug: 'jwt-structure-and-verification',
    title: 'JWTs: what is inside one, and why decoding is not verifying',
    description: 'A JSON Web Token is three Base64url segments. Reading them is trivial and proves nothing, the signature is what carries the security.',
    excerpt: 'Anyone holding a JWT can read every claim in it. That is by design, and it is the single most misunderstood thing about the format.',
    category: 'dev',
    tags: ['jwt', 'auth', 'security'],
    published: '2026-08-23',
    relatedTools: ['jwt-decoder', 'base64', 'hash-generator'],
    takeaways: [
      'A JWT is base64url encoded, not encrypted. Anyone holding one can read the payload.',
      'Decoding is not verifying. Reading the claims proves nothing until the signature is checked against a key you trust.',
      'The server must decide which algorithm it accepts. Taking that instruction from the token itself is the alg none vulnerability.',
      'A signed token cannot be revoked before it expires, which is why short lifetimes matter.',
    ],
    words: 677,
  },

  {
    slug: 'regex-patterns-that-actually-come-up',
    title: 'Regex without the mystique: the patterns that actually come up',
    description: 'Anchors, greedy versus lazy matching, groups and the backtracking trap. The regex knowledge that covers most real tasks.',
    excerpt: 'Most regex frustration comes from three things: forgetting anchors, not knowing greedy matching exists, and trying to validate email addresses.',
    category: 'dev',
    tags: ['regex', 'text-processing', 'validation'],
    published: '2026-08-27',
    relatedTools: ['regex-tester', 'find-replace', 'extract-emails', 'extract-urls', 'text-cleaner'],
    takeaways: [
      'Without anchors a pattern matches anywhere in the string, which is the most common reason a validation passes when it should not.',
      'Quantifiers are greedy by default, so add ? to make them lazy when a match swallows more than intended.',
      'Nested quantifiers over overlapping alternatives cause catastrophic backtracking and can hang a process on one input.',
      'No regex validates an email address. The only real check is sending a message to it.',
    ],
    words: 731,
  },

  {
    slug: 'uuid-v4-vs-v7-which-one',
    title: 'UUID v4 or v7? What changed and which to use for database keys',
    description: 'Random UUIDs fragment database indexes. Version 7 puts a timestamp in front, making identifiers sortable while staying unpredictable enough.',
    excerpt: 'v4 is 122 random bits and has served well for twenty years. v7 fixes the one place it hurts: as a primary key in a B-tree index.',
    category: 'dev',
    tags: ['uuid', 'databases', 'identifiers'],
    published: '2026-09-03',
    relatedTools: ['uuid-generator', 'random-string', 'timestamp-converter'],
    takeaways: [
      'A v4 UUID is entirely random, so inserts land all over a B-tree index and the write path suffers as the table grows.',
      'A v7 UUID puts a timestamp in the leading bits, so new rows are appended and locality is restored.',
      'Neither is a secret. A v7 leaks its creation time by design, and a v4 is not an authorisation token.',
      'Store them as 16 binary bytes rather than as 36-character text if the table is large.',
    ],
    words: 703,
  },

  {
    slug: 'colour-contrast-and-wcag',
    title: 'Colour contrast: what the WCAG numbers mean and how to hit them',
    description: 'The 4.5:1 ratio comes from a luminance formula. Understanding it explains why light grey on white fails and how to fix a palette that does.',
    excerpt: 'Low-contrast text is the most common accessibility failure on the web, and one of the easiest to fix, once you know which number you are aiming at and why.',
    category: 'dev',
    tags: ['accessibility', 'wcag', 'colour', 'css'],
    published: '2026-09-08',
    relatedTools: ['contrast-checker', 'color-converter', 'palette-color', 'gradient-generator', 'glassmorphism'],
    takeaways: [
      'The ratio compares relative luminance, not perceived brightness, so two colours can look distinct and still fail.',
      'The thresholds are 4.5:1 for body text and 3:1 for large text and interface components.',
      'Fix contrast by adjusting lightness rather than hue, so the palette keeps its character.',
      'An automated pass does not mean readable. Placeholder text, disabled states and text over images are where it breaks.',
    ],
    words: 661,
  },

  {
    slug: 'qr-codes-what-is-encoded',
    title: 'QR codes: what is actually encoded, and how to make one that scans',
    description: 'A QR code is just text with error correction. Knowing that explains why some codes are dense, why some fail to scan, and why the logo in the middle works.',
    excerpt: 'There is no database behind a QR code. Everything it knows is printed in the squares, which is why a long URL makes a code nobody can scan.',
    category: 'dev',
    tags: ['qr', 'encoding', 'url'],
    published: '2026-09-10',
    relatedTools: ['qr-generator', 'url-parser', 'url-encoder', 'slug-generator'],
    takeaways: [
      'A QR code contains the text itself, not a lookup key. Shorter text means fewer modules and an easier scan.',
      'Error correction is why a logo in the middle still works, and at level H up to 30% of the code can be obscured.',
      'The quiet zone, four modules of blank margin, is part of the specification. Codes fail without it.',
      'Numeric and uppercase-only content packs far more densely, which is why upper-casing a URL path shortens the code.',
    ],
    words: 851,
  },

  {
    slug: 'what-a-formatter-actually-does',
    title: 'Prettify or minify: what formatters actually do to your code',
    description: 'Formatting and minifying are the same parse-and-print operation with opposite goals. Knowing what each one is allowed to change explains the edge cases.',
    excerpt: 'A formatter throws your whitespace away and prints the syntax tree again. Everything surprising about formatters follows from that.',
    category: 'dev',
    tags: ['formatting', 'minify', 'tooling'],
    published: '2026-09-11',
    relatedTools: ['html-formatter', 'css-formatter', 'js-formatter', 'sql-formatter', 'xml-formatter'],
    takeaways: [
      'A formatter parses the code to a syntax tree and prints it fresh. Your original whitespace is discarded, not adjusted.',
      'That is why a formatter refuses to run on a syntax error: it cannot print a tree it could not build.',
      'Minifying HTML is riskier than minifying CSS or JS, because whitespace between inline elements is significant.',
      'Never minify SQL to send to a database. Formatting SQL is for reading it; the engine does not care.',
    ],
    words: 863,
  },

  {
    slug: 'three-kinds-of-escaping',
    title: 'URL encoding, HTML entities and MIME types: three things people mix up',
    description: 'Percent-encoding, entity encoding and content types solve different problems. Using the wrong one produces bugs that look identical.',
    excerpt: 'The same ampersand needs three different treatments depending on where it is going. Getting them confused is how &amp;amp;amp; ends up on a page.',
    category: 'dev',
    tags: ['encoding', 'url', 'html', 'mime'],
    published: '2026-09-13',
    relatedTools: ['url-encoder', 'html-entity', 'mime-checker', 'url-parser'],
    takeaways: [
      'Percent-encoding protects characters from a URL parser. Entity encoding protects them from an HTML parser. They are not interchangeable.',
      'encodeURI is for a whole URL, encodeURIComponent is for one piece of one. Using the wrong one is the classic query-string bug.',
      'Double encoding shows up as %2520 or &amp;amp;. Both mean something encoded an already-encoded string.',
      'A file extension is a naming convention; the MIME type from the magic bytes is what a program actually acts on.',
    ],
    words: 969,
  },

  {
    slug: 'cleaning-a-block-of-text',
    title: 'Cleaning a block of text: the operations worth doing in order',
    description: 'Deduplicating, sorting, trimming and case conversion are trivial individually. The order you run them in decides whether the result is right.',
    excerpt: 'Removing duplicates before trimming whitespace leaves you with duplicates. Most text-cleaning frustration is an ordering problem, not a tool problem.',
    category: 'dev',
    tags: ['text', 'cleanup', 'case'],
    published: '2026-09-14',
    relatedTools: ['text-cleaner', 'remove-duplicates-text', 'sort-lines', 'remove-empty-lines', 'case-converter', 'word-counter', 'lorem-ipsum', 'reverse-text', 'extract-phones', 'extract-hashtags'],
    takeaways: [
      'Trim whitespace before deduplicating, or two identical lines with different trailing spaces both survive.',
      'Case conversion is not symmetric: going to a flat case loses word boundaries you cannot always recover.',
      'Sorting a CSV by lines will sort the header row into the middle of the data.',
      'Word counts differ between tools because "word" is not defined. Find out which definition your limit uses.',
    ],
    words: 854,
  },

  {
    slug: 'yaml-json-and-tabular-interchange',
    title: 'YAML, JSON and TSV: picking a format for config and interchange',
    description: 'JSON has no comments, YAML has the Norway problem, and TSV avoids the quoting mess CSV is famous for. Each trade matters somewhere.',
    excerpt: 'YAML turns the country code NO into the boolean false. That is not a bug report, it is in the specification, and it is why config formats need choosing carefully.',
    category: 'dev',
    tags: ['yaml', 'json', 'tsv', 'config'],
    published: '2026-09-12',
    relatedTools: ['yaml-formatter', 'json-to-csv', 'tsv-converter', 'json-formatter'],
    takeaways: [
      'YAML 1.1 reads unquoted no, off and n as false, which silently corrupts country codes and short answers.',
      'JSON has no comments and no trailing commas, which is exactly why it is a poor configuration format and a good wire format.',
      'Indentation in YAML must be spaces. A tab is a parse error, and it is invisible.',
      'TSV avoids CSVs quoting problems because tabs almost never appear inside data, but it cannot represent a value containing a tab.',
    ],
    words: 968,
  },

  {
    slug: 'gradients-and-palettes',
    title: 'Gradients and palettes: why yours goes grey in the middle',
    description: 'Interpolating between two colours in sRGB passes through a dead zone. Understanding why explains most disappointing gradients and palettes.',
    excerpt: 'Blend blue into yellow and you get a muddy grey halfway. That is not your eye, it is the colour space doing arithmetic that does not match perception.',
    category: 'dev',
    tags: ['colour', 'gradients', 'css'],
    published: '2026-09-13',
    relatedTools: ['gradient-generator', 'palette-color', 'color-converter', 'contrast-checker'],
    takeaways: [
      'Interpolating in sRGB passes through desaturated grey. Interpolating in OKLCH stays vivid.',
      'A gradient between complementary hues will always cross a dull midpoint unless you add a stop or change colour space.',
      'Harmony rules generate candidate hues; they do not produce a usable palette until lightness is adjusted per hue.',
      'Yellow at the same lightness value as blue looks much brighter, so never derive a palette by rotating hue alone.',
    ],
    words: 820,
  },

  {
    slug: 'find-replace-and-extraction',
    title: 'Find, replace and extract: getting structure out of unstructured text',
    description: 'Bulk editing and pattern extraction solve the same problem from opposite ends, and both have the same failure mode.',
    excerpt: 'Replace all instances of "cat" and you have just changed "category", "concatenate" and "location". Word boundaries exist for a reason.',
    category: 'dev',
    tags: ['regex', 'text', 'extraction'],
    published: '2026-09-14',
    relatedTools: ['find-replace', 'regex-tester', 'extract-hashtags', 'extract-emails', 'extract-urls', 'reverse-text'],
    takeaways: [
      'Plain find and replace matches inside words. Use word boundaries unless you want to change "category" while replacing "cat".',
      'Replace-all is unrecoverable once you close the tab. Check the match count before committing.',
      'No regex fully validates an email address. Extraction is for finding candidates, not for deciding they are real.',
      'Test the pattern on the awkward cases first, not the obvious ones.',
    ],
    words: 906,
  },

  {
    slug: 'alt-text-and-accessible-documents',
    title: 'Alt text, headings and the accessibility work that also helps search',
    description: 'The things that make a page or a document usable with a screen reader are largely the same things that make it legible to a crawler.',
    excerpt: 'Alt text is not a caption and not a keyword bin. Getting it right takes one question: what would a sighted reader lose if the image vanished?',
    category: 'dev',
    tags: ['accessibility', 'alt-text', 'headings'],
    published: '2026-09-11',
    relatedTools: ['pdf-ocr', 'docx-to-html', 'contrast-checker', 'html-formatter'],
    takeaways: [
      'Alt text answers what a reader would lose if the image failed to load, not what the image contains.',
      'A purely decorative image needs alt="" so screen readers skip it. Omitting the attribute reads the filename instead.',
      'Heading levels are an outline, not sizes. Skipping from h2 to h4 breaks navigation for screen reader users.',
      'A scanned PDF is unreadable to a screen reader and to a crawler for exactly the same reason: it has no text.',
    ],
    words: 847,
  },

  {
    slug: 'http-status-codes-that-matter',
    title: 'HTTP status codes: the handful that decide what search engines do',
    description: 'A 301 and a 302 look the same to a visitor and mean opposite things to a crawler. So do a 404 and a soft 404.',
    excerpt: 'Moving a page with the wrong redirect code throws away everything that page had earned. The difference is one digit.',
    category: 'dev',
    tags: ['http', 'status-codes', 'redirects', 'seo'],
    published: '2026-09-12',
    relatedTools: ['url-parser', 'mime-checker', 'user-agent-parser', 'url-encoder'],
    takeaways: [
      'A 301 is permanent and passes ranking to the new URL. A 302 is temporary and keeps the old one indexed.',
      'A soft 404 is a missing page that returns 200 with a friendly message, and it keeps dead URLs in the index.',
      'Chained redirects lose value at each hop, so point old URLs directly at the final destination.',
      'A 410 tells a crawler the page is deliberately gone, which removes it faster than a 404.',
    ],
    words: 756,
  },

  {
    slug: 'cron-expressions-explained',
    title: 'Cron expressions: reading the five fields without guessing',
    description: 'Five numbers decide when a job runs. Day-of-month and day-of-week interact in a way that surprises almost everyone.',
    excerpt: 'A schedule that should fire monthly fires every Monday as well. The two day fields are combined with OR, not AND.',
    category: 'dev',
    tags: ['cron', 'scheduling', 'timezones', 'automation'],
    published: '2026-09-12',
    relatedTools: ['timestamp-converter', 'timezone-converter', 'regex-tester', 'unit-converter'],
    takeaways: [
      'The five fields are minute, hour, day of month, month, day of week, in that order.',
      'If both day fields are restricted, most implementations run when either matches, not when both do.',
      'Cron runs in the server time zone, so daylight saving can skip a run or fire it twice.',
      'Step values like */15 divide the range, but */7 on days does not mean weekly.',
    ],
    words: 828,
  },

  {
    slug: 'cleaning-a-url-before-sharing',
    title: 'What you are actually sharing when you paste a link',
    description: 'Most shared links carry tracking parameters, and some carry a session token. Both survive being forwarded.',
    excerpt: 'The link you copied from your address bar may identify you to everyone you send it to, and occasionally log them in as you.',
    category: 'dev',
    tags: ['urls', 'tracking', 'privacy', 'sharing'],
    published: '2026-09-13',
    relatedTools: ['url-parser', 'url-encoder', 'extract-urls', 'slug-generator'],
    takeaways: [
      'Everything after ? is parameters, and utm_, fbclid and gclid can all be deleted without breaking the link.',
      'Some links carry a session or invite token that grants access to whoever holds it.',
      'URLs leak through the Referer header to the next site you visit, so a secret in a URL is not private.',
      'Shortened links hide the destination entirely, which is the point of them and the problem with them.',
    ],
    words: 807,
  },
  {
    slug: 'mime-types-and-file-signatures',
    title: 'MIME types, magic bytes and why a file opens as the wrong thing',
    description: 'The extension, the declared MIME type and the actual bytes are three separate claims about a file, and any of them can be wrong.',
    excerpt: 'An upload rejects your PNG for not being a PNG. The extension says one thing, the first eight bytes say another, and the server believes the bytes.',
    category: 'dev',
    tags: ['mime', 'file-formats', 'uploads'],
    published: '2026-09-16',
    relatedTools: ['mime-checker', 'image-convert', 'zip-extractor'],
    takeaways: [
      'A file extension is a naming convention, not a fact about the contents. Renaming .webp to .png converts nothing.',
      'Most formats start with a signature — magic bytes — that identifies them regardless of name. That is what strict uploaders check.',
      'Browsers decide what to do with a response from the Content-Type header, not the URL, which is why a served file can download instead of displaying.',
      'Never trust a client-supplied MIME type on the server. It is chosen by whoever uploaded the file.',
    ],
    words: 862,
  },
  {
    slug: 'what-a-user-agent-string-says',
    title: 'What a user agent string actually says about you',
    description: 'The user agent is a browser identifying itself in a format shaped by decades of compatibility hacks, and it is losing detail on purpose.',
    excerpt: 'Every browser claims to be Mozilla. The string is part identification, part historical fiction, and it is a weaker signal every year.',
    category: 'dev',
    tags: ['user-agent', 'browsers', 'privacy'],
    published: '2026-09-15',
    relatedTools: ['user-agent-parser', 'url-parser'],
    takeaways: [
      'Every mainstream browser begins its user agent with "Mozilla/5.0" for compatibility with 1990s server sniffing. It carries no information.',
      'Browsers are freezing and reducing the string on purpose, so version and platform detail is deliberately less precise than it used to be.',
      'Detect capabilities, not browsers. Feature detection stays correct when the string changes; version comparisons do not.',
      'A user agent is trivially spoofed, so it is never a security control — but combined with other signals it still contributes to fingerprinting.',
    ],
    words: 726,
  },
];
