import { BlogPost } from '../types';

export const IMAGE_POSTS: BlogPost[] = [
  {
    slug: 'jpeg-png-webp-avif-which-format',
    title: 'JPEG, PNG, WebP or AVIF: picking the right image format',
    description: 'Four formats, four different jobs. A practical comparison of compression, transparency, browser support and when each one is the wrong choice.',
    excerpt: 'Saving a screenshot as JPEG makes the text fuzzy. Saving a photo as PNG makes the file eight times larger. Both mistakes come from the same gap in knowledge.',
    category: 'image',
    tags: ['formats', 'jpeg', 'png', 'webp', 'avif'],
    published: '2026-08-07',
    relatedTools: ['image-convert', 'image-compressor', 'svg-converter', 'image-metadata'],
    takeaways: [
      'Text, sharp edges and flat colour want PNG. Photographs want JPEG or WebP. The mismatch costs either size or quality.',
      'WebP is the sensible default for your own website and the wrong thing to email a client or send to a printer.',
      'JPEG has no transparency at all, which decides the question whenever a cut-out background is involved.',
      'Always convert from the highest-quality original, because each conversion inherits the previous one artefacts.',
    ],
    words: 831,
  },

  {
    slug: 'how-image-compression-works',
    title: 'How image compression works: lossy, lossless, and the quality slider',
    description: 'What the quality slider actually changes, why 80 is usually the sweet spot, and why re-saving the same image twice makes it worse.',
    excerpt: 'The number in the quality box is not a percentage of anything. Knowing what it really controls explains most of the odd results people get.',
    category: 'image',
    tags: ['compression', 'quality', 'jpeg'],
    published: '2026-08-14',
    relatedTools: ['image-compressor', 'image-convert', 'batch-resize'],
    takeaways: [
      'Lossless finds redundancy and keeps every pixel. Lossy discards detail the eye is least likely to miss.',
      'The quality number is not a percentage. It selects a quantisation table, and the scale is not linear or comparable between encoders.',
      'Quality 80 is the usual sweet spot, with most of the saving and little visible cost.',
      'Generation loss is real: every re-save of a JPEG compounds the damage, so always work from the original.',
    ],
    words: 761,
  },

  {
    slug: 'resize-vs-compress-images',
    title: 'Resize or compress? The difference that decides your file size',
    description: 'Resizing changes pixel dimensions, compressing changes how those pixels are stored. Reaching for the wrong one is why images end up blurry and still too big.',
    excerpt: 'A 300 DPI setting does nothing for an image on a website. Pixels are the only unit the screen understands, and understanding that fixes a lot of frustration.',
    category: 'image',
    tags: ['resize', 'compression', 'dpi'],
    published: '2026-08-21',
    relatedTools: ['image-resize', 'image-compressor', 'batch-resize', 'image-crop'],
    takeaways: [
      'File size scales with pixel count, so halving both dimensions removes about three quarters of the data before any compression.',
      'DPI is metadata and means nothing on a screen. Only pixel dimensions matter for web use.',
      'Upscaling interpolates and adds no detail. If the pixels were never captured, no tool recovers them.',
      'Resize first, then compress. Doing it the other way wastes the compression on pixels you are about to discard.',
    ],
    words: 632,
  },

  {
    slug: 'remove-image-background-in-browser',
    title: 'How AI background removal works, and where it still fails',
    description: 'Segmentation models can cut a subject out of a photo in seconds. Understanding what the model is doing tells you which photos will work and which will not.',
    excerpt: 'The model is not "finding the person". It is assigning every pixel a probability of being foreground, which explains exactly why hair and glass give it trouble.',
    category: 'image',
    tags: ['ai', 'background-removal', 'segmentation'],
    published: '2026-08-29',
    relatedTools: ['ai-bg-remover', 'image-convert', 'image-crop', 'image-editor'],
    takeaways: [
      'The model predicts an alpha value per pixel, so the output is a soft mask rather than a yes-or-no cutout.',
      'Edges are the hard part, and hair, fur, glass and motion blur are where results fall apart.',
      'A clear subject against a contrasting, evenly lit background predicts a good result better than any setting.',
      'Expect to touch up the edges on anything that will be seen at full size.',
    ],
    words: 738,
  },

  {
    slug: 'optimise-images-for-web-performance',
    title: 'Image optimisation for web performance: the four things that matter',
    description: 'Images are usually the largest thing on a page. Format, dimensions, layout stability and loading strategy account for nearly all of the gain.',
    excerpt: 'Most pages ship images several times larger than they display, in a format from 1992, with no dimensions set. Fixing those three things is most of the work.',
    category: 'image',
    tags: ['performance', 'web', 'core-web-vitals'],
    published: '2026-09-05',
    relatedTools: ['image-compressor', 'batch-resize', 'image-convert', 'svg-converter'],
    takeaways: [
      'Serving an image far larger than it is displayed is the single biggest waste, and the most common one.',
      'Always set width and height, because without them the page reflows as images load and that is a layout shift penalty.',
      'Load the hero image eagerly and lazy-load everything below the fold. Lazy-loading the hero makes the page measurably slower.',
      'Modern formats save real bytes, but only after the dimensions are already right.',
    ],
    words: 724,
  },

  {
    slug: 'favicon-sizes-and-formats',
    title: 'Favicons: the sizes that still matter and the ones that do not',
    description: 'Browsers, phones and search results all want a different icon. Here is the short list that actually covers them without shipping fourteen files.',
    excerpt: 'The advice online still lists a dozen icon sizes from 2014. Four files cover essentially everything today, and one of them is not an icon at all.',
    category: 'image',
    tags: ['favicon', 'icons', 'svg'],
    published: '2026-09-10',
    relatedTools: ['ico-generator', 'svg-converter', 'image-resize', 'image-convert'],
    takeaways: [
      'Four files cover modern browsers: an SVG, a 32px PNG, a 180px Apple touch icon and a 512px PNG for installs.',
      'favicon.ico is still worth shipping because bare requests for /favicon.ico happen with no HTML involved.',
      'A .ico is a container holding several sizes, which is why it is not simply a renamed PNG.',
      'Design the 16px version separately. A detailed logo shrunk to 16px becomes a smudge.',
    ],
    words: 794,
  },

  {
    slug: 'putting-things-on-top-of-images',
    title: 'Watermarks, annotations, memes and collages: drawing on an image',
    description: 'Four tools that all composite something onto a picture, and the surprisingly different things they are each good for.',
    excerpt: 'Whether you are marking a proof, redacting a screenshot or building a comparison, you are doing the same operation with very different stakes.',
    category: 'image',
    tags: ['watermark', 'annotation', 'collage'],
    published: '2026-09-11',
    relatedTools: ['image-watermark', 'image-draw', 'image-collage', 'meme-generator', 'drawing'],
    takeaways: [
      'Compositing is destructive. The output is a flat picture, so keep the original separately.',
      'Drawing a black box over a screenshot is real removal, unlike the same action in a PDF, because the pixels are replaced.',
      'A watermark at the edge is cropped off in seconds. Across the middle at low opacity is the version that survives.',
      'For a collage, resize the inputs to a common dimension first, or the layout engine will do it for you and badly.',
    ],
    words: 813,
  },

  {
    slug: 'rotate-flip-and-sharpen',
    title: 'Rotate, flip and sharpen: the small fixes, and which ones cost quality',
    description: 'Three corrections that look equally trivial. One is free, one is free, and one permanently alters your image and cannot be undone.',
    excerpt: 'Your phone photo appears sideways on the web but upright in the gallery. Nothing is broken, and the fix is one byte.',
    category: 'image',
    tags: ['rotate', 'exif', 'sharpen'],
    published: '2026-09-12',
    relatedTools: ['image-rotate', 'image-flip', 'image-sharpen', 'image-adjust'],
    takeaways: [
      'A photo that looks sideways on the web is usually upright with an EXIF orientation tag that something ignored.',
      'Rotating by 90 degree steps is lossless. Rotating by an arbitrary angle resamples every pixel.',
      'Sharpening adds contrast at edges. It cannot recover detail that was never captured, and it is not reversible.',
      'Sharpen last, after resizing, and only enough to counteract what the resize softened.',
    ],
    words: 771,
  },

  {
    slug: 'data-uris-when-to-inline-an-image',
    title: 'Base64 images: when inlining helps and when it costs you',
    description: 'Turning an image into a data URI removes a request and adds 33% to its size. Knowing which trade matters tells you when to do it.',
    excerpt: 'A data URI embeds the picture in the markup. That is occasionally the right call and usually a way to make a page slower.',
    category: 'image',
    tags: ['base64', 'data-uri', 'performance'],
    published: '2026-09-12',
    relatedTools: ['image-to-base64', 'base64-to-image', 'image-compressor', 'svg-converter'],
    takeaways: [
      'Base64 encodes 3 bytes as 4 characters, so an inlined image is always about 33% larger than the file.',
      'Inlined images cannot be cached separately, so a data URI in a stylesheet is re-downloaded whenever that stylesheet changes.',
      'Worth it for tiny icons, single-file documents and email signatures. Not worth it for photographs.',
      'An SVG inlined as plain markup beats the same SVG base64-encoded, because it compresses and does not pay the 33%.',
    ],
    words: 822,
  },

  {
    slug: 'cropping-well',
    title: 'Cropping well: aspect ratios, the rule nobody needs, and safe areas',
    description: 'Cropping is the cheapest way to improve a photograph and the easiest way to have it mangled by a platform that crops it again.',
    excerpt: 'Every platform re-crops your image to its own ratio. If you do not decide where the subject sits, an algorithm will decide for you.',
    category: 'image',
    tags: ['crop', 'aspect-ratio', 'editing'],
    published: '2026-09-13',
    relatedTools: ['image-crop', 'image-editor', 'image-resize', 'batch-resize'],
    takeaways: [
      'Cropping discards pixels permanently. Resizing rescales them. Doing both in the wrong order loses resolution you needed.',
      'Crop to the aspect ratio the destination uses, or the destination will crop it for you and probably badly.',
      'Keep the subject away from the edges so a re-crop to a different ratio still works.',
      'Crop before resizing, because the crop decides how many pixels you are scaling from.',
    ],
    words: 769,
  },

  {
    slug: 'passport-and-id-photo-specs',
    title: 'Getting a passport or visa photo to pass the checker',
    description: 'Photo rejections are nearly always dimensions, head ratio or background. Each one is measurable before you submit.',
    excerpt: 'Portals reject photos for reasons they rarely explain. Four measurements account for almost all of it, and you can check every one yourself.',
    category: 'image',
    tags: ['photo', 'resize', 'crop', 'passport'],
    published: '2026-09-09',
    relatedTools: ['image-crop', 'image-resize', 'image-convert', 'image-compressor'],
    takeaways: [
      'Head height as a proportion of the frame is the specification people miss, and it is the most common rejection.',
      'Crop to the required aspect ratio first, then resize to the pixel dimensions. The other order wastes resolution.',
      'A file-size cap is met by lowering JPEG quality, not by shrinking dimensions below the stated minimum.',
      'Never upscale. If the source is smaller than the required dimensions, retake the photo.',
    ],
    words: 820,
  },

  {
    slug: 'social-preview-images',
    title: 'Why your link preview looks wrong when you share it',
    description: 'Open Graph images get cropped differently by every platform. Designing for the safe area is what stops your title being cut in half.',
    excerpt: 'You set an image, share the link, and the preview crops your logo off. The image was right; the safe area was not.',
    category: 'image',
    tags: ['open-graph', 'social', 'images'],
    published: '2026-09-09',
    relatedTools: ['image-resize', 'image-crop', 'image-convert', 'image-compressor'],
    takeaways: [
      '1200x630 is the right default, but every platform re-crops it, so keep text well inside the middle.',
      'og:image needs an absolute URL. A relative path silently produces no preview at all.',
      'Previews are cached hard, so a corrected image usually needs a new filename before it shows up.',
      'Use JPEG or PNG rather than WebP here, because social scrapers are less consistent about it than browsers.',
    ],
    words: 677,
  },

  {
    slug: 'why-colours-look-different-on-each-screen',
    title: 'Why the same image looks different on every screen',
    description: 'Colour profiles decide how stored numbers become visible colour. Strip one and your careful red becomes somebody else orange.',
    excerpt: 'The photo that looked right on your laptop is washed out on the client phone. The pixels are identical; the interpretation is not.',
    category: 'image',
    tags: ['colour', 'srgb', 'profiles', 'display'],
    published: '2026-09-11',
    relatedTools: ['image-convert', 'color-converter', 'image-metadata', 'image-compressor'],
    takeaways: [
      'A pixel value is a coordinate, not a colour. The profile is what says which colour that coordinate means.',
      'Stripping the profile from a wide-gamut image makes it look dull or oversaturated, because it is then read as sRGB.',
      'Export to sRGB for the web. It is the one profile every browser and device agrees about.',
      'Editing metadata is not the same as converting. Assigning a profile relabels; converting recalculates the pixels.',
    ],
    words: 826,
  },

  {
    slug: 'product-photos-for-listings',
    title: 'Product photos that pass a marketplace listing check',
    description: 'Amazon, Etsy and Shopify each impose minimum pixels, background rules and aspect ratios. The overlap between them is a single workable spec.',
    excerpt: 'Listings get rejected for three things: too few pixels, the wrong background, and a product that fills too little of the frame.',
    category: 'image',
    tags: ['ecommerce', 'product-photos', 'resize', 'background'],
    published: '2026-09-11',
    relatedTools: ['ai-bg-remover', 'image-crop', 'image-resize', 'image-compressor'],
    takeaways: [
      'Most marketplaces want at least 1600px on the long edge so their zoom feature works; some accept 1000px without zoom.',
      'A pure white background is a hard requirement on main images for several platforms, not a style preference.',
      'The product should fill about 85% of the frame. Too much empty space is a common rejection.',
      'Shoot on white, remove the background, then crop and resize. Doing it in that order avoids halo edges.',
    ],
    words: 737,
  },

  {
    slug: 'screenshots-for-bug-reports',
    title: 'Screenshots that actually help: annotation, redaction and what leaks',
    description: 'A screenshot sent for support often contains more than the bug. Browser tabs, notifications and the clipboard all end up in frame.',
    excerpt: 'A black box over text in a screenshot really does delete it, unlike in a PDF. Blurring, on the other hand, has been reversed.',
    category: 'image',
    tags: ['screenshots', 'annotation', 'redaction', 'privacy'],
    published: '2026-09-12',
    relatedTools: ['image-draw', 'image-crop', 'image-metadata', 'image-compressor'],
    takeaways: [
      'A solid black box over pixels is genuine removal, because the original values are overwritten.',
      'Blur and pixellation are reversible on text and have been broken in practice. Use an opaque fill.',
      'Crop first. The fastest way to remove a notification banner or a browser tab is to not include it.',
      'A useful bug screenshot shows the error, the URL and enough context to locate the page.',
    ],
    words: 741,
  },
  {
    slug: 'making-a-gif-worth-sending',
    title: 'Making a GIF that is not 40 megabytes',
    description: 'GIF is a 1987 format with 256 colours and no real compression for photos. Knowing what it is bad at is how you get a small, clean loop.',
    excerpt: 'A five-second clip becomes a 40 MB GIF and a 900 KB MP4 of identical quality. GIF is not a video format, and that is the whole explanation.',
    category: 'image',
    tags: ['gif', 'video', 'compression', 'formats'],
    published: '2026-09-16',
    relatedTools: ['gif-maker', 'gif-converter', 'video-trim', 'video-converter'],
    takeaways: [
      'GIF stores at most 256 colours per frame and cannot compress across frames the way a video codec does, so photographic content explodes in size.',
      'Duration, frame rate and dimensions each multiply the size. Cut length first, then width, then frames per second.',
      'Flat-colour screen recordings are what GIF is genuinely good at. Camera footage almost never is.',
      'If the destination accepts a silent looping MP4 or WebM, use that instead: same motion, a fraction of the bytes.',
    ],
    words: 748,
  },
  {
    slug: 'reading-text-off-an-image',
    title: 'Reading text off an image: what OCR gets right and where it fails',
    description: 'OCR turns pixels into characters, and its accuracy is decided before it runs — by resolution, contrast and whether the page is straight.',
    excerpt: 'The difference between 99% and 80% accuracy is usually the photo, not the engine. Most of the fix happens before any text is recognised.',
    category: 'image',
    tags: ['ocr', 'text', 'scanning'],
    published: '2026-09-15',
    relatedTools: ['ocr-image', 'ai-ocr', 'image-adjust', 'image-crop'],
    takeaways: [
      'OCR wants roughly 300 DPI of text. A phone photo of a page from a distance is often below that, and no engine recovers detail that was never captured.',
      'Straighten, crop and raise contrast before recognising. Skew of more than a couple of degrees measurably lowers accuracy.',
      'Columns, tables and forms fail at the layout stage, not the character stage: the characters are right and the reading order is wrong.',
      'Always proofread digits. A misread character in a word is obvious; a misread digit in an amount is not.',
    ],
    words: 735,
  },
];
