import { BlogPost } from '../types';

export const MEDIA_POSTS: BlogPost[] = [
  {
    slug: 'mp4-is-not-a-codec',
    title: 'MP4 is not a codec: containers, codecs and why a file will not play',
    description: 'A video file has a container and at least two codecs inside it. Playback failures are almost always a codec problem wearing a container name.',
    excerpt: 'Renaming a file to .mp4 changes nothing about what is inside it. The extension names the box; the thing that fails to play is the contents.',
    category: 'image',
    tags: ['video', 'codecs', 'mp4', 'formats'],
    published: '2026-09-17',
    updated: '2026-09-29',
    relatedTools: ['video-converter', 'mov-to-mp4', 'webm-to-mp4', 'mp4-to-mp3'],
    takeaways: [
      'MP4, MKV and MOV are containers. H.264, HEVC, VP9 and AV1 are video codecs. AAC, MP3 and Opus are audio codecs. A file has one container and usually two codecs.',
      'A file that opens with sound but no picture, or picture but no sound, has a codec the player cannot decode. The container was fine.',
      'H.264 with AAC in an MP4 is the combination that plays essentially everywhere. Anything newer trades compatibility for file size.',
      'Changing the extension by renaming does not convert anything. It only makes the mismatch harder to diagnose.',
    ],
    words: 1006,
  },
  {
    slug: 'compressing-a-video-without-ruining-it',
    title: 'Compressing a video without ruining it',
    description: 'Video size is bit rate times duration. Knowing which of resolution, bit rate and frame rate to cut first is what keeps a compressed clip watchable.',
    excerpt: 'A 200 MB clip has to reach 25 MB. There are three dials that make it smaller and only one of them is usually the right one to turn first.',
    category: 'image',
    tags: ['video', 'compression', 'bitrate'],
    published: '2026-09-17',
    updated: '2026-09-29',
    relatedTools: ['video-compressor', 'video-converter', 'mp4-to-mp3'],
    takeaways: [
      'File size is roughly bit rate × duration. Resolution and frame rate matter because they determine what bit rate looks acceptable.',
      'Cut bit rate first, resolution second, frame rate last. Frame rate is the most visible of the three on motion.',
      'For a hard limit, work backwards: target bits = limit × 8 ÷ duration in seconds, then subtract the audio bit rate.',
      'Trimming dead air at the start and end is free compression. Duration is a multiplier on everything else.',
    ],
    words: 867,
  },
  {
    slug: 'extracting-audio-from-video',
    title: 'Getting the audio out of a video, and what quality survives',
    description: 'Extracting audio can be a lossless copy or a re-encode. Which one you get decides whether the result is identical to the original track.',
    excerpt: 'The audio in a video is already a separate stream. Pulling it out can be a copy rather than a conversion, and the difference is audible.',
    category: 'image',
    tags: ['audio', 'video', 'extraction', 'podcast'],
    published: '2026-09-17',
    updated: '2026-09-29',
    relatedTools: ['mp4-to-mp3', 'audio-converter', 'm4a-to-mp3', 'wav-to-mp3'],
    takeaways: [
      'The audio track in an MP4 is usually AAC. Saving it as .m4a copies it bit for bit; saving it as MP3 re-encodes and loses a little more.',
      'Converting a lossy track to WAV does not restore quality. It only stops compressing what is already damaged.',
      'For speech, 64–96 kbps mono is clean and small. Stereo and high bit rates are wasted on a single voice.',
      'Transcription works from the audio, so extracting the track first is often faster than feeding it a whole video file.',
    ],
    words: 823,
  },
  {
    slug: 'subtitles-srt-and-burned-in-captions',
    title: 'Subtitles: SRT files, embedded tracks and burned-in captions',
    description: 'Three different ways a caption reaches a viewer, with different consequences for editing, accessibility and whether the text can be turned off.',
    excerpt: 'Captions can be a separate file, a track inside the video, or pixels drawn permanently onto the frames. Only one of those is reversible.',
    category: 'image',
    tags: ['subtitles', 'captions', 'accessibility', 'video'],
    published: '2026-09-17',
    updated: '2026-09-29',
    relatedTools: ['srt-to-vtt', 'vtt-to-srt', 'mp4-to-mp3'],
    takeaways: [
      'An SRT is a plain text file of numbered cues with start and end timestamps. It can be edited in any text editor.',
      'A sidecar file can be turned off, indexed and corrected. Burned-in captions cannot be removed without re-encoding from the original.',
      'Social feeds that autoplay muted are the real reason burned-in captions exist. Everywhere else, a real subtitle track is better.',
      'Auto-generated captions need a pass for names, numbers and punctuation before they are worth publishing.',
    ],
    words: 884,
  },
];
