import { BlogPost } from '../types';

export const NUMBERS_POSTS: BlogPost[] = [
  {
    slug: 'timestamps-time-zones-and-the-missing-hour',
    title: 'Unix timestamps, UTC and the off-by-one-hour bug',
    description: 'A timestamp is a count of seconds with no time zone in it. Almost every date bug comes from adding a zone too early or too late.',
    excerpt: 'Your report is right eleven months of the year and wrong for one week in spring. That is daylight saving, and the fix is upstream of the report.',
    category: 'numbers',
    tags: ['timestamps', 'timezones', 'dates'],
    published: '2026-09-13',
    relatedTools: ['timestamp-converter', 'timezone-converter', 'age-calculator'],
    takeaways: [
      'A Unix timestamp has no time zone. It is a count of seconds since 1970 in UTC, and a zone is applied only when it is displayed.',
      'Store UTC, display local. Storing local time loses which offset was in force and cannot be recovered later.',
      'Offsets like +05:30 are not time zones. A zone is a set of rules that changes; an offset is a single number at one instant.',
      'A 10-digit number is seconds and a 13-digit one is milliseconds. Mixing them puts dates in 1970 or in the year 54,000.',
    ],
    words: 907,
  },

  {
    slug: 'the-maths-behind-the-calculators',
    title: 'EMI, GST and percentages: the formulas the calculators are running',
    description: 'Loan instalments, tax-inclusive prices and percentage change all have one formula each. Knowing them tells you when an answer is wrong.',
    excerpt: 'A 20% rise followed by a 20% fall does not get you back to where you started. That is not a rounding error, and the same confusion makes tax and loan figures wrong.',
    category: 'numbers',
    tags: ['finance', 'percentages', 'units'],
    published: '2026-09-14',
    relatedTools: ['emi-calculator', 'gst-calculator', 'percentage-calc', 'unit-converter', 'bmi-calculator', 'number-to-words', 'roman-numerals', 'scientific-calc'],
    takeaways: [
      'Percentage change is not symmetric. Down 20% then up 20% leaves you 4% below where you started.',
      'Removing GST from an inclusive price is division, not subtraction. Taking 18% off a 118 price does not give 100.',
      'EMI is fixed but its split is not: early instalments are mostly interest, which is why early repayment saves so much.',
      'Temperature is the one unit conversion with an offset, so a ratio that works for length does not work for Celsius.',
    ],
    words: 1075,
  },

  {
    slug: 'dates-numbers-across-locales',
    title: 'The same number written six ways: dates and separators across locales',
    description: 'A file that reads 03/04/2026 says two different dates depending on who opens it, and 1,234 means two different numbers.',
    excerpt: 'Half the world reads 03/04/2026 as March and half as April. Neither is wrong, which is exactly why the format cannot be trusted.',
    category: 'numbers',
    tags: ['locales', 'dates', 'currency', 'formatting'],
    published: '2026-09-14',
    relatedTools: ['number-to-words', 'unit-converter', 'timezone-converter', 'gst-calculator'],
    takeaways: [
      '03/04/2026 is March in the US and April almost everywhere else, and nothing in the file says which.',
      'In much of Europe the decimal separator is a comma, so 1,234 is one and a bit rather than a thousand.',
      'Store an unambiguous machine value and format it for display. Never store a formatted string.',
      'The Indian system groups digits in lakhs and crores, so the same figure is written differently from the same data.',
    ],
    words: 922,
  },

  {
    slug: 'mean-median-and-percentiles',
    title: 'Mean, median and percentiles: reading a number honestly',
    description: 'An average is one number standing in for a distribution. Which average you pick decides what it conceals.',
    excerpt: 'A mean response time of four hours can describe a service where nothing takes four hours. The median and a percentile say what actually happens.',
    category: 'numbers',
    tags: ['statistics', 'averages', 'percentiles', 'reporting'],
    published: '2026-09-14',
    relatedTools: ['percentage-calc', 'scientific-calc', 'csv-editor', 'unit-converter'],
    takeaways: [
      'The mean is pulled by outliers; the median is not. Skewed data needs the median.',
      'A percentile answers what the bad case looks like, which an average cannot.',
      'Always report the sample size next to an average, because 4.8 from six ratings is not 4.8 from six hundred.',
      'Averaging percentages or rates without weighting them by volume gives the wrong answer.',
    ],
    words: 707,
  },

  {
    slug: 'compound-interest-and-saving',
    title: 'Compound interest: the arithmetic behind savings and debt',
    description: 'The same formula grows a savings balance and a credit card balance. Compounding frequency and fees decide how much of it you keep.',
    excerpt: 'A quoted rate and what you actually earn are different numbers. The gap is compounding frequency, and it has a name.',
    category: 'numbers',
    tags: ['interest', 'savings', 'apr', 'compounding'],
    published: '2026-09-14',
    relatedTools: ['emi-calculator', 'percentage-calc', 'scientific-calc', 'gst-calculator'],
    takeaways: [
      'Compounding means earning interest on previous interest, so the balance grows by a curve rather than a line.',
      'A nominal rate and the effective annual rate differ whenever interest compounds more than once a year.',
      'Time matters more than rate. Starting earlier beats a slightly better rate over any long period.',
      'Credit card interest usually compounds daily, which is why a balance grows faster than the headline rate suggests.',
    ],
    words: 748,
  },
  {
    slug: 'unit-conversion-and-its-assumptions',
    title: 'Unit conversion is not one multiplication',
    description: 'Some conversions are a factor, some need an offset, and some depend on what you are measuring. Mixing them up is how spacecraft get lost.',
    excerpt: 'Twice the temperature in Celsius is not twice the temperature. Half the conversions people treat as multiplication are not multiplication.',
    category: 'numbers',
    tags: ['units', 'conversion', 'measurement'],
    published: '2026-09-15',
    relatedTools: ['unit-converter', 'scientific-calc', 'percentage-calc'],
    takeaways: [
      'Ratio scales (length, mass, time) convert by multiplication. Interval scales (Celsius, Fahrenheit) need an offset, so doubling them is meaningless.',
      'A US gallon and an imperial gallon differ by about 20%, and both are called "gallon". The same trap applies to tons, pints and fluid ounces.',
      'Converting mass to volume requires a density, which is a property of the substance. A cup of flour and a cup of water are not the same weight.',
      'Round only at the end. Rounding mid-chain compounds the error through every later step.',
    ],
    words: 774,
  },
  {
    slug: 'gst-invoices-and-rounding',
    title: 'GST on an invoice: inclusive, exclusive and where the rounding goes',
    description: 'Tax arithmetic is simple until rounding, line items and reverse calculations meet. Most invoice disputes are one paise of rounding order.',
    excerpt: 'Adding 18% and then removing 18% does not return the original number. That single fact explains most tax-inclusive pricing confusion.',
    category: 'numbers',
    tags: ['gst', 'tax', 'invoices', 'rounding'],
    published: '2026-09-15',
    relatedTools: ['gst-calculator', 'percentage-calc', 'number-to-words'],
    takeaways: [
      'To remove tax from an inclusive amount, divide by (1 + rate). Subtracting the rate percentage gives a different and wrong answer.',
      'Round per line item, then total — rounding the total after summing unrounded lines produces figures that do not reconcile.',
      'A 100 discounted by 10% then taxed at 18% differs from one taxed then discounted. Order is a policy decision, not arithmetic.',
      'Amounts in words on an invoice exist to make tampering obvious, which is why the words and the figures must be generated from the same number.',
    ],
    words: 810,
  },
];
