import { BlogPost } from '../types';

export const PRIVACY_POSTS: BlogPost[] = [
  {
    slug: 'why-client-side-tools-are-safer',
    title: 'Why browser-based tools are safer than upload-based ones',
    description: 'The difference is not a privacy policy. It is whether a copy of your file exists on someone else\'s hardware at all.',
    excerpt: 'A promise to delete your file after an hour is only as good as the company making it. Never sending the file removes the question entirely.',
    category: 'privacy',
    tags: ['privacy', 'client-side', 'wasm'],
    published: '2026-08-11',
    relatedTools: ['pdf-merge', 'image-compressor', 'ai-bg-remover', 'json-formatter'],
    takeaways: [
      'An upload touches a CDN, a load balancer, application servers, object storage, logs and backups before anyone deletes anything.',
      'Most exposure happens without malice: a misconfigured bucket, a retained log line, a backup snapshot nobody thought about.',
      'Browsers can now do the work locally, so the upload is a choice rather than a technical necessity.',
      'You can tell which kind you are using: a local tool works with the network disconnected.',
    ],
    words: 805,
  },

  {
    slug: 'exif-metadata-in-your-photos',
    title: 'What your photos reveal: EXIF metadata and how to remove it',
    description: 'Photos carry GPS coordinates, timestamps, device serial numbers and more. What is stored, which platforms strip it, and how to check your own files.',
    excerpt: 'A photo posted from home can contain the coordinates of the room it was taken in, accurate to a few metres, in a field nobody thinks to look at.',
    category: 'privacy',
    tags: ['exif', 'metadata', 'photos', 'gps'],
    published: '2026-08-19',
    relatedTools: ['image-metadata', 'image-convert', 'image-compressor', 'pdf-metadata'],
    takeaways: [
      'A photo can carry GPS coordinates, a timestamp, the device model and even the camera body serial number.',
      'The embedded thumbnail is not always regenerated when the main image is edited, so a cropped photo can still contain the original.',
      'Platforms strip metadata inconsistently, and stripping on upload does not help a file you send directly.',
      'Documents carry the same problem in a different place: author names, revision counts and editing time.',
    ],
    words: 707,
  },

  {
    slug: 'what-happens-when-you-upload-a-file',
    title: 'What actually happens to a file you upload to a free online tool',
    description: 'A walk through the infrastructure an uploaded document passes through, and which parts a "deleted after 1 hour" policy typically does not cover.',
    excerpt: 'The file does not go to one computer. Following its actual path explains why deletion promises are harder to keep than they sound.',
    category: 'privacy',
    tags: ['privacy', 'uploads', 'data-retention'],
    published: '2026-08-26',
    relatedTools: ['pdf-compress', 'pdf-merge', 'image-compressor', 'pdf-redact'],
    takeaways: [
      'A single upload is written in several places: the application server, object storage, log files at several layers, and backups.',
      'Deleted after one hour normally means the primary copy. Backup snapshots and log entries outlive it.',
      'Terms of service frequently grant a licence to process the file and name subprocessors you have never heard of.',
      'Match the care to the document. A meme and a medical record do not deserve the same default.',
    ],
    words: 748,
  },

  {
    slug: 'cookies-tracking-and-what-you-can-control',
    title: 'Cookies, tracking and what you can actually control',
    description: 'First-party versus third-party cookies, fingerprinting, and which browser settings genuinely change what is collected about you.',
    excerpt: 'Clicking "reject all" on a consent banner does less than most people assume, and there are a handful of settings that do considerably more.',
    category: 'privacy',
    tags: ['cookies', 'tracking', 'fingerprinting', 'gdpr'],
    published: '2026-09-02',
    relatedTools: ['user-agent-parser', 'url-parser', 'secure-notes'],
    takeaways: [
      'First-party cookies keep you logged in. Third-party cookies were what followed you between sites.',
      'As third-party cookies decline, tracking has moved to server-side tagging and first-party identifiers, which are harder to see.',
      'Fingerprinting uses properties of your device, so clearing cookies does not reset it.',
      'Blocking third-party cookies, using a content blocker and turning on tracking protection are what actually help.',
    ],
    words: 810,
  },

  {
    slug: 'what-your-browser-announces',
    title: 'What your browser announces before you click anything',
    description: 'The user agent string, the headers and the capability list your browser sends on every request, and how little of it you can change.',
    excerpt: 'Chrome on Windows identifies itself as Mozilla, Safari and Gecko all at once. The reason is thirty years of websites guessing wrong.',
    category: 'privacy',
    tags: ['user-agent', 'fingerprinting', 'headers'],
    published: '2026-09-13',
    relatedTools: ['user-agent-parser', 'url-parser', 'mime-checker'],
    takeaways: [
      'Every user agent string claims to be Mozilla, because sites used to sniff for it and serve worse pages to anything else.',
      'The user agent alone is weak identification, but combined with screen size, fonts and timezone it becomes a near-unique fingerprint.',
      'Browsers are freezing and reducing the user agent string precisely because it became a tracking vector.',
      'Feature detection is both more reliable and less privacy-invasive than parsing the user agent.',
    ],
    words: 916,
  },

  {
    slug: 'a-backup-that-actually-works',
    title: 'A backup that works when you need it',
    description: 'Most backup plans fail in the same three ways: one copy, same building, never tested. The 3-2-1 rule exists because of each.',
    excerpt: 'Sync is not backup. If a file is deleted or encrypted on your laptop, the service faithfully deletes or encrypts it everywhere else too.',
    category: 'privacy',
    tags: ['backup', 'storage', 'ransomware'],
    published: '2026-09-12',
    relatedTools: ['zip-creator', 'file-checksum', 'batch-zip', 'secure-notes'],
    takeaways: [
      'Sync replicates mistakes. A deletion or an encryption propagates to every synced device within seconds.',
      '3-2-1 means three copies, on two kinds of media, with one off-site, and each number fixes a specific failure.',
      'A backup you have never restored from is a hypothesis, not a backup.',
      'Checksums are what let you prove a restored file is identical to the original rather than assuming it.',
    ],
    words: 875,
  },

  {
    slug: 'browser-permissions-and-extensions',
    title: 'What you agree to when you install a browser extension',
    description: 'An extension asking to read and change all your data on all websites is asking for exactly that, including your banking session.',
    excerpt: 'Extensions run inside every page you open. A popular one changing hands is a supply-chain event, and it happens regularly.',
    category: 'privacy',
    tags: ['extensions', 'permissions', 'browser'],
    published: '2026-09-13',
    relatedTools: ['image-metadata', 'user-agent-parser', 'secure-notes', 'url-parser'],
    takeaways: [
      'Read and change all your data on all websites means the extension can read any page you are logged into.',
      'Extensions update silently, so the code you audited is not necessarily the code running tomorrow.',
      'Popular extensions get bought, and the buyer inherits the install base and the permissions.',
      'Site access can be narrowed to on click or specific sites, which removes most of the exposure.',
    ],
    words: 791,
  },

  {
    slug: 'what-incognito-mode-does-not-do',
    title: 'Private browsing: what it hides, and from whom',
    description: 'Incognito mode hides your activity from other people using your device. It hides nothing from the sites, your employer or your provider.',
    excerpt: 'Private browsing is local amnesia, not invisibility. The confusion is common enough that Chrome had to rewrite its own warning screen.',
    category: 'privacy',
    tags: ['incognito', 'private-browsing', 'tracking'],
    published: '2026-09-12',
    relatedTools: ['url-parser', 'image-metadata', 'secure-notes', 'user-agent-parser'],
    takeaways: [
      'Private mode stops history, cookies and form data being written to your device. That is the whole feature.',
      'Your employer, your network and every site you visit see exactly the same as they would normally.',
      'Logging into an account in private mode identifies you completely, which defeats the point.',
      'Downloads and bookmarks you save during the session survive it.',
    ],
    words: 714,
  },

  {
    slug: 'email-tracking-pixels',
    title: 'How an email knows you opened it',
    description: 'A one-pixel image and a rewritten link are enough to record when you read a message, where you were and what you clicked.',
    excerpt: 'Every link in a marketing email usually points at the sender, not the destination. That redirect is what records the click.',
    category: 'privacy',
    tags: ['email', 'tracking', 'pixels', 'links'],
    published: '2026-09-13',
    relatedTools: ['extract-urls', 'url-parser', 'html-markdown', 'text-cleaner'],
    takeaways: [
      'A tracking pixel is a unique image URL, so loading it tells the sender you opened the message and roughly where you were.',
      'Blocking remote images stops open tracking almost entirely, and most mail clients now do it by default.',
      'Links are usually rewritten to route through the sender, so the click is recorded even with images off.',
      'Apple Mail Privacy Protection preloads images for everyone, which makes open rates largely meaningless now.',
    ],
    words: 809,
  },

  {
    slug: 'saving-a-web-page-properly',
    title: 'Saving a web page so it is still readable later',
    description: 'Bookmarks break, screenshots are not searchable and Save As often produces a folder that no longer renders. Each has a fix.',
    excerpt: 'A bookmark saves an address, not a page. When the page changes or disappears, the bookmark points at nothing.',
    category: 'privacy',
    tags: ['archiving', 'bookmarks', 'pdf', 'offline'],
    published: '2026-09-14',
    relatedTools: ['html-to-pdf', 'html-markdown', 'text-to-pdf', 'pdf-ocr'],
    takeaways: [
      'A bookmark stores a URL. If the page is edited or removed, the bookmark preserves nothing.',
      'PDF keeps the appearance and stays searchable, which makes it the right default for evidence.',
      'Markdown keeps the words and structure in a tiny, durable, diffable file.',
      'A screenshot keeps neither searchable text nor structure, so use it only alongside something else.',
    ],
    words: 757,
  },
];
