import type { ElementType } from 'react';
import {
  Activity, AlignLeft, AlignVerticalJustifyCenter, Aperture, ArrowLeftRight, ArrowUpDown,
  BadgeCheck, BarChart2, Binary, Blend, BookLock, BookOpen,
  Braces, Calculator, Calendar, ChevronsLeftRight, Clapperboard, Clock,
  Code, Code2, Combine, CopyX, CreditCard, Crop,
  Database, Dices, DollarSign, Edit3, Eraser, Eye,
  EyeOff, FileAudio, FileCode, FileCode2, FileInput, FileJson,
  FileMinus2, FileOutput, FilePlus2, FileSearch, FileSpreadsheet, FileText,
  FileType, Film, FlipHorizontal, Focus, FolderArchive, FormInput,
  GalleryVertical, Gauge, GitCompare, Globe, Globe2, GripVertical,
  Hash, Image, ImageDown, Images, Info, KeyRound,
  KeySquare, Languages, Layers, LayoutGrid, LayoutPanelLeft, Link,
  Link2, Lock, Mail, Maximize2, MessageSquare, Mic,
  Minimize, Minimize2, Monitor, MonitorPlay, Music, Music2,
  PackageOpen, PackagePlus, Paintbrush, Palette, PenLine, PenTool,
  Percent, Phone, Presentation, QrCode, Receipt, RefreshCw,
  Regex, RemoveFormatting, Replace, Rewind, RotateCw, Ruler,
  ScanFace, ScanSearch, ScanText, Scissors, Sheet, ShieldCheck,
  ShieldOff, Sigma, SlidersHorizontal, Sparkles, SpellCheck, Stamp,
  Subtitles, SunMedium, SwatchBook, Table, Table2, Tags,
  Trash2, Type, Undo2, Unlock, Volume2, VolumeX,
  Wind, Wrench, ZoomIn,
} from 'lucide-react';

export const TOOL_ICONS: Record<string, ElementType> = {
  Activity, AlignLeft, AlignVerticalJustifyCenter, Aperture, ArrowLeftRight, ArrowUpDown,
  BadgeCheck, BarChart2, Binary, Blend, BookLock, BookOpen,
  Braces, Calculator, Calendar, ChevronsLeftRight, Clapperboard, Clock,
  Code, Code2, Combine, CopyX, CreditCard, Crop,
  Database, Dices, DollarSign, Edit3, Eraser, Eye,
  EyeOff, FileAudio, FileCode, FileCode2, FileInput, FileJson,
  FileMinus2, FileOutput, FilePlus2, FileSearch, FileSpreadsheet, FileText,
  FileType, Film, FlipHorizontal, Focus, FolderArchive, FormInput,
  GalleryVertical, Gauge, GitCompare, Globe, Globe2, GripVertical,
  Hash, Image, ImageDown, Images, Info, KeyRound,
  KeySquare, Languages, Layers, LayoutGrid, LayoutPanelLeft, Link,
  Link2, Lock, Mail, Maximize2, MessageSquare, Mic,
  Minimize, Minimize2, Monitor, MonitorPlay, Music, Music2,
  PackageOpen, PackagePlus, Paintbrush, Palette, PenLine, PenTool,
  Percent, Phone, Presentation, QrCode, Receipt, RefreshCw,
  Regex, RemoveFormatting, Replace, Rewind, RotateCw, Ruler,
  ScanFace, ScanSearch, ScanText, Scissors, Sheet, ShieldCheck,
  ShieldOff, Sigma, SlidersHorizontal, Sparkles, SpellCheck, Stamp,
  Subtitles, SunMedium, SwatchBook, Table, Table2, Tags,
  Trash2, Type, Undo2, Unlock, Volume2, VolumeX,
  Wind, Wrench, ZoomIn,
};

export const resolveToolIcon = (name: string, fallback: ElementType): ElementType =>
  TOOL_ICONS[name] ?? fallback;
